[
  typography: [
    name: "typography",
    args: [
      color: [
        "base",
        "primary",
        "white",
        "natural",
        "secondary",
        "dark",
        "success",
        "warning",
        "danger",
        "info",
        "silver",
        "misc",
        "dawn",
        "inherit"
      ],
      size: [
        "extra_small",
        "small",
        "medium",
        "large",
        "extra_large",
        "double_large",
        "triple_large",
        "quadruple_large"
      ],
      type: [
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p",
        "strong",
        "em",
        "dl",
        "dt",
        "dd",
        "figure",
        "figcaption",
        "abbr",
        "mark",
        "small",
        "s",
        "u",
        "cite",
        "del"
      ],
      only: [
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p",
        "strong",
        "em",
        "dl",
        "dt",
        "dd",
        "figure",
        "figcaption",
        "abbr",
        "mark",
        "small",
        "s",
        "u",
        "cite",
        "del"
      ],
      helpers: [],
      module: ""
    ],
    optional: [],
    necessary: []
  ]
]
